### PR TITLE
mm-mainnet-docs-WIP

### PR DESCRIPTION
**Pull request by kennacudo**
This doc is WIP and not ready for merge yet

### CODE REVIEW

**Comment by mmckennacudo** [comment]
hi, @mlukanova and @kstoykov, please can you assist me with completing this documentation for mainnet. I have done what I can, but need you to fill in the blanks as and when we have the relevant info. I've prepared this for your guidance re what i need: https://www.notion.so/cudo/Information-needed-for-mainnet-docs-9477f162d27442d7aab4f0201f08ef4f
Let me know when you have finished and i will then get the doc reviewed.

**Comment by ethanill** [comment]
An Ethereum node is no longer required for mainnet Validators so this can be removed from the docs https://docs.cudos.org/build/hardware.html#ethereum-node

**Comment by mmckennacudo** [comment]
@jgtormo do you mean the Developer guide currently in the testnet section, but updated for  mainnet? I don't know what in that guide needs to change between testnet and mainnet, so don't know what to ask for. Can you provide me with details of what needs to change in that doc between testnet and mainnet.

**Comment by kennacudo** [comment]
@jgtormo per our conversation on slack on wednesday, I have added 3 commits for the developer docs, (docs copied from testnet, then some edits i've made on each doc) which will also need input from Limechain as well as  a final review from a Cudo SME. I've also added comments in the [info requirements Notion doc.](https://www.notion.so/cudo/Information-needed-for-mainnet-docs-9477f162d27442d7aab4f0201f08ef4f)

**Comment by ethanill** [comment]
@mlukanova are you ok to resolve conflicts ahead of merge?

**Pull request merged**
